"""
Abstract base classes and protocols for AI services.

This module defines the interfaces that AI services must implement
to ensure consistency and testability across the application.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import List, Protocol
from datetime import datetime
from decimal import Decimal


@dataclass
class ClassificationResult:
    """Result of review classification by AI service."""

    sentiment: str  # positive, negative, neutral
    topics: List[str]  # food_quality, service, ambiance, price, cleanliness
    urgency: str  # low, medium, high
    competitor_mentioned: bool
    confidence_score: float
    processing_time_ms: int
    ai_model: str


@dataclass
class ReviewText:
    """Review text with metadata for batch processing."""

    id: str
    text: str
    language: str
    business_id: str


@dataclass
class BusinessContext:
    """Business context for AI advisor responses."""

    business_id: str
    business_name: str
    avg_rating: float
    total_reviews: int
    recent_sentiment_trend: str
    top_topics: List[str]
    competitor_mentions: int


@dataclass
class AdvisorResponse:
    """Response from business advisor AI service."""

    message: str
    language: str
    confidence_score: float
    processing_time_ms: int
    ai_model: str
    cost_usd: Decimal


@dataclass
class WeeklyReport:
    """Weekly business report generated by AI advisor."""

    business_id: str
    report_period_start: datetime
    report_period_end: datetime
    summary: str
    action_items: List[str]
    sentiment_analysis: str
    top_themes: List[str]
    competitor_mentions: int
    language: str
    ai_model: str


class ReviewClassifierProtocol(Protocol):
    """Protocol for review classification AI services."""

    async def classify_review(
        self, text: str, language: str = "en"
    ) -> ClassificationResult:
        """Classify a single review for sentiment, topics, and urgency."""
        ...

    async def classify_batch(
        self, reviews: List[ReviewText]
    ) -> List[ClassificationResult]:
        """Classify multiple reviews in a single API call for cost efficiency."""
        ...


class BusinessAdvisorProtocol(Protocol):
    """Protocol for business advisory AI services."""

    async def generate_response(
        self, message: str, context: BusinessContext, language: str = "en"
    ) -> AdvisorResponse:
        """Generate contextual business advice based on review data."""
        ...

    async def generate_report(
        self, business_data: BusinessContext, language: str = "en"
    ) -> WeeklyReport:
        """Generate comprehensive weekly business report."""
        ...


class CostTracker(ABC):
    """Abstract base class for AI usage cost tracking."""

    @abstractmethod
    async def log_usage(
        self,
        business_id: str,
        ai_service: str,
        operation: str,
        tokens_used: int,
        cost_usd: Decimal,
        processing_time_ms: int,
    ) -> None:
        """Log AI service usage for cost tracking."""
        pass

    @abstractmethod
    async def get_monthly_cost(self, business_id: str) -> Decimal:
        """Get current month's AI usage cost for a business."""
        pass

    @abstractmethod
    async def check_cost_limit(self, business_id: str) -> bool:
        """Check if business is within cost limits."""
        pass
