"""Initial database schema with all tables

Revision ID: 460cd8fe3aa5
Revises:
Create Date: 2025-11-05 15:03:42.127178

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "460cd8fe3aa5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("subscription_tier", sa.String(length=50), nullable=False),
        sa.Column(
            "cost_limit_monthly", sa.DECIMAL(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "businesses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("google_place_id", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("avg_rating", sa.DECIMAL(precision=3, scale=2), nullable=True),
        sa.Column("total_reviews", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("google_place_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("language_preference", sa.String(length=5), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("idx_users_email", "users", ["email"], unique=False)
    op.create_table(
        "ai_usage_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("ai_service", sa.String(length=50), nullable=False),
        sa.Column("operation", sa.String(length=50), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.DECIMAL(precision=10, scale=6), nullable=False),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ai_usage_logs_business_created",
        "ai_usage_logs",
        ["business_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "daily_analytics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("avg_rating", sa.DECIMAL(precision=3, scale=2), nullable=True),
        sa.Column(
            "sentiment_positive", sa.DECIMAL(precision=5, scale=2), nullable=True
        ),
        sa.Column("sentiment_neutral", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column(
            "sentiment_negative", sa.DECIMAL(precision=5, scale=2), nullable=True
        ),
        sa.Column("review_count", sa.Integer(), nullable=True),
        sa.Column("top_topics", sa.JSON(), nullable=True),
        sa.Column("competitor_mentions", sa.Integer(), nullable=True),
        sa.Column("response_rate", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column(
            "avg_response_time_hours", sa.DECIMAL(precision=8, scale=2), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_id", "date", name="uq_daily_analytics_business_date"
        ),
    )
    op.create_index(
        "idx_daily_analytics_business_date",
        "daily_analytics",
        ["business_id", "date"],
        unique=False,
    )
    op.create_table(
        "monthly_cost_summaries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column(
            "classification_cost", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column("chat_cost", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("report_cost", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("total_cost", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("cost_limit", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("usage_percentage", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_id", "month", name="uq_monthly_cost_business_month"
        ),
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("author_name", sa.String(length=255), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_id", "external_id", "source", name="uq_review_external"
        ),
    )
    op.create_index("idx_reviews_business_id", "reviews", ["business_id"], unique=False)
    op.create_index(
        "idx_reviews_published_at", "reviews", ["published_at"], unique=False
    )
    op.create_table(
        "user_business_access",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("permission_level", sa.String(length=50), nullable=False),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "business_id"),
    )
    op.create_table(
        "classifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("sentiment", sa.String(length=20), nullable=False),
        sa.Column("topics", sa.JSON(), nullable=False),
        sa.Column("urgency", sa.String(length=20), nullable=False),
        sa.Column("competitor_mentioned", sa.Boolean(), nullable=True),
        sa.Column("confidence_score", sa.DECIMAL(precision=4, scale=3), nullable=False),
        sa.Column("ai_model", sa.String(length=50), nullable=False),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_classifications_review_id", "classifications", ["review_id"], unique=False
    )
    op.create_index(
        "idx_classifications_urgency", "classifications", ["urgency"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_classifications_urgency", table_name="classifications")
    op.drop_index("idx_classifications_review_id", table_name="classifications")
    op.drop_table("classifications")
    op.drop_table("user_business_access")
    op.drop_index("idx_reviews_published_at", table_name="reviews")
    op.drop_index("idx_reviews_business_id", table_name="reviews")
    op.drop_table("reviews")
    op.drop_table("monthly_cost_summaries")
    op.drop_index("idx_daily_analytics_business_date", table_name="daily_analytics")
    op.drop_table("daily_analytics")
    op.drop_index("idx_ai_usage_logs_business_created", table_name="ai_usage_logs")
    op.drop_table("ai_usage_logs")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_table("users")
    op.drop_table("businesses")
    op.drop_table("organizations")
    # ### end Alembic commands ###
