"""Add GDPR compliance tables

Revision ID: 63237937fff6
Revises: 460cd8fe3aa5
Create Date: 2025-11-05 18:31:55.174270

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "63237937fff6"
down_revision = "460cd8fe3aa5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_breach_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("breach_id", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("affected_data_types", sa.JSON(), nullable=False),
        sa.Column("affected_users_count", sa.Integer(), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("contained_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("mitigation_steps", sa.JSON(), nullable=True),
        sa.Column("authority_notified", sa.Boolean(), nullable=True),
        sa.Column("authority_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("users_notified", sa.Boolean(), nullable=True),
        sa.Column("users_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("breach_id"),
    )
    op.create_index(
        "idx_data_breach_logs_breach_id",
        "data_breach_logs",
        ["breach_id"],
        unique=False,
    )
    op.create_index(
        "idx_data_breach_logs_discovered",
        "data_breach_logs",
        ["discovered_at"],
        unique=False,
    )
    op.create_index(
        "idx_data_breach_logs_severity", "data_breach_logs", ["severity"], unique=False
    )
    op.create_table(
        "data_retention_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("data_type", sa.String(length=100), nullable=False),
        sa.Column("retention_period_days", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("legal_basis", sa.String(length=100), nullable=True),
        sa.Column("auto_cleanup_enabled", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_type"),
    )
    op.create_index(
        "idx_data_retention_policies_type",
        "data_retention_policies",
        ["data_type"],
        unique=False,
    )
    op.create_table(
        "consent_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("consent_type", sa.String(length=50), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("legal_basis", sa.String(length=50), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_consent_records_created", "consent_records", ["created_at"], unique=False
    )
    op.create_index(
        "idx_consent_records_type", "consent_records", ["consent_type"], unique=False
    )
    op.create_index(
        "idx_consent_records_user", "consent_records", ["user_id"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_conversations_business_user",
        "conversations",
        ["business_id", "user_id"],
        unique=False,
    )
    op.create_index(
        "idx_conversations_updated", "conversations", ["updated_at"], unique=False
    )
    op.create_table(
        "data_subject_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("request_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("request_details", sa.JSON(), nullable=True),
        sa.Column("response_data", sa.JSON(), nullable=True),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_data_subject_requests_requested",
        "data_subject_requests",
        ["requested_at"],
        unique=False,
    )
    op.create_index(
        "idx_data_subject_requests_status",
        "data_subject_requests",
        ["status"],
        unique=False,
    )
    op.create_index(
        "idx_data_subject_requests_type",
        "data_subject_requests",
        ["request_type"],
        unique=False,
    )
    op.create_index(
        "idx_data_subject_requests_user",
        "data_subject_requests",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("ai_model", sa.String(length=50), nullable=True),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.DECIMAL(precision=10, scale=6), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_conversation_messages_conversation",
        "conversation_messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        "idx_conversation_messages_created",
        "conversation_messages",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "review_responses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_generated", sa.Boolean(), nullable=True),
        sa.Column("ai_model", sa.String(length=50), nullable=True),
        sa.Column("tone_analysis", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_review_responses_published",
        "review_responses",
        ["published_at"],
        unique=False,
    )
    op.create_index(
        "idx_review_responses_review", "review_responses", ["review_id"], unique=False
    )
    op.create_index(
        "idx_review_responses_user", "review_responses", ["user_id"], unique=False
    )
    op.alter_column(
        "ai_usage_logs",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_usage_logs",
        "business_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "businesses",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "businesses",
        "organization_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "classifications",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "classifications",
        "review_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "daily_analytics",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "daily_analytics",
        "business_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "monthly_cost_summaries",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "monthly_cost_summaries",
        "business_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "organizations",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "reviews",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "reviews",
        "business_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_business_access",
        "user_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_business_access",
        "business_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_business_access",
        "granted_by",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "organization_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "organization_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_business_access",
        "granted_by",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "user_business_access",
        "business_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_business_access",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "reviews",
        "business_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "reviews",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "organizations",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "monthly_cost_summaries",
        "business_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "monthly_cost_summaries",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "daily_analytics",
        "business_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "daily_analytics",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "classifications",
        "review_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "classifications",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "businesses",
        "organization_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "businesses",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_usage_logs",
        "business_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_usage_logs",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.drop_index("idx_review_responses_user", table_name="review_responses")
    op.drop_index("idx_review_responses_review", table_name="review_responses")
    op.drop_index("idx_review_responses_published", table_name="review_responses")
    op.drop_table("review_responses")
    op.drop_index(
        "idx_conversation_messages_created", table_name="conversation_messages"
    )
    op.drop_index(
        "idx_conversation_messages_conversation", table_name="conversation_messages"
    )
    op.drop_table("conversation_messages")
    op.drop_index("idx_data_subject_requests_user", table_name="data_subject_requests")
    op.drop_index("idx_data_subject_requests_type", table_name="data_subject_requests")
    op.drop_index(
        "idx_data_subject_requests_status", table_name="data_subject_requests"
    )
    op.drop_index(
        "idx_data_subject_requests_requested", table_name="data_subject_requests"
    )
    op.drop_table("data_subject_requests")
    op.drop_index("idx_conversations_updated", table_name="conversations")
    op.drop_index("idx_conversations_business_user", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("idx_consent_records_user", table_name="consent_records")
    op.drop_index("idx_consent_records_type", table_name="consent_records")
    op.drop_index("idx_consent_records_created", table_name="consent_records")
    op.drop_table("consent_records")
    op.drop_index(
        "idx_data_retention_policies_type", table_name="data_retention_policies"
    )
    op.drop_table("data_retention_policies")
    op.drop_index("idx_data_breach_logs_severity", table_name="data_breach_logs")
    op.drop_index("idx_data_breach_logs_discovered", table_name="data_breach_logs")
    op.drop_index("idx_data_breach_logs_breach_id", table_name="data_breach_logs")
    op.drop_table("data_breach_logs")
    # ### end Alembic commands ###
